% Probability that the queue of user R is empty
% B - queue size
% q1 = attempt probability of user 1
% qR = attempt probability of user R
% qU = robability of user U requesting a file from external resources

function [ t0, rho, probState0, probStateNot0, probStateFull ] =...
    statesProb(B, q1, qR, qU, ph, alpha,...
               P_1toD, P_1toDwhenR, P_1toDwhenBS, P_1toDwhenBSandR, ... 
               P_1toR, P_1toRwhenBS, ...
               P_RtoD, P_RtoDwhen1, P_RtoDwhenBS, P_RtoDwhenBSand1 )

    % Probability that relay's queue Q is increased by 1 packet when Q = 0       
    a1 =  q1 * (1 - qU) * (1 - P_1toD) * P_1toR  ...
        + q1 * qU * ph * (1 - P_1toDwhenR )* P_1toR + ...        
        + q1 * qU * (1-ph) * alpha * (1 - P_1toDwhenBS)*P_1toRwhenBS+ ...
        + q1 * qU * (1-ph) * (1-alpha) * (1 - P_1toD) * P_1toR;

    % Probability that relay's queue Q is decreased by 1 packet when Q > 0     

    b0 = qR*(1-q1)*(1-qU)*P_RtoD ...
       + qR*(1-q1)*qU*(1-ph)*alpha*P_RtoDwhenBS ...
       + qR*(1-q1)*qU*(1-ph)*(1-alpha)*P_RtoD ...
       + qR*q1*(1-qU)*( P_RtoDwhen1* (P_1toDwhenR +(1-P_1toDwhenR)*(1-P_1toR)) )...
       + qR*q1*qU*(1-ph)*alpha* (P_RtoDwhenBSand1* (P_1toDwhenBSandR + (1-P_1toDwhenBSandR)*(1-P_1toDwhenBS)) )...
       + qR*q1*qU*(1-ph)*(1-alpha) * (P_RtoDwhen1*(P_1toDwhenR + (1-P_1toDwhenR)*(1-P_1toR)) );
       
    % Probability that relay's queue Q is increased by 1 packet when Q > 0     

    b2 = q1*qR*(1-qU)*(1-P_RtoDwhen1)*(1-P_1toDwhenR)*P_1toR ...
       + q1*qR*qU*(1-ph)*alpha*(1-P_RtoDwhenBSand1)*(1-P_1toDwhenBSandR)*P_1toRwhenBS ...
       + q1*qR*qU*(1-ph)*(1-alpha)*(1-P_RtoDwhen1)*(1-P_1toDwhenR)*P_1toR ...
       ...
       + q1*(1-qR)* ( (1-qU)*(1-P_1toD)*P_1toR + qU*ph*(1-P_1toDwhenR)*P_1toR) ...
       + q1*(1-qR)*qU*(1-ph)*alpha*(1-P_1toDwhenBS)*P_1toRwhenBS ...
       + q1*(1-qR)*qU*(1-ph)*(1-alpha)*(1-P_1toD)*P_1toR;

       
    t0  = a1 / b0;
    rho = b2 / b0;
    assert(rho~=1);

    probState0    = 1/(1 + (t0 * (1-rho^(B))/(1-rho)) );
    probStateNot0 = 1 - probState0;
    probStateFull = rho^(B-1) * t0 *probState0;
    
end
